#!/usr/bin/env bash
#
# Coupang first-connection + order-routine live-proof BOOTSTRAP. Mints a single opaque run id and a single
# opaque approval id for this run, and writes the shared run env that run-backend-local.sh and preflight.sh
# both read. The approval id is what the backend live-call interlock (CoupangLiveCallGuard) is armed with and
# what the operator's single-use "Seated and ready." grant binds to (docs/sellerops_live_approval_contract.md).
#
# Both ids are ENVIRONMENT identifiers, never a credential or auth token. Re-run this to start a fresh run —
# a new approval id invalidates the old one, so a stale approval can never be reused. NO Coupang call, no
# credential, no server started here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_DIR="$HERE/.run"
RUN_ENV="$RUN_DIR/current.env"

# Which proof this run is for. It is bound into the run env, so a grant for one is never a grant for the
# other: preflight refuses a kind that is not its own, and each kind has its OWN expected DB baseline —
# `orders` starts from nothing, `inquiries` starts from an already-connected account. Unlike the credential
# bootstrap (where omission would reach the more dangerous run), both kinds here are read-only marketplace
# GETs, so `orders` stays the default and the existing documented flow is unchanged.
KIND="${1:-orders}"
case "$KIND" in
  orders)
    KIND_WHAT="first connection + ORDER_SUMMARY routine (starts from an empty DB)" ;;
  inquiries)
    KIND_WHAT="상품별 고객문의 acquisition + routine (starts from a CONNECTED account with a stored credential)" ;;
  inquiries-dedupe)
    KIND_WHAT="re-sweep the SAME window to prove idempotency (starts from an account that has already collected)" ;;
  orders-resync)
    # Order Context Foundation v1 §8.1 gate 1. The ONLY READ_ONLY kind here, and it is read-only
    # because it does exactly one thing: re-collect ORDER_SUMMARY on an account that is ALREADY
    # connected. The credential is somebody else's job — it is handed over by its own bootstrap
    # (wing-credential-bootstrap.sh handoff), under its own manifest, on its own day. Bundling a
    # credential write into this run is what made the `orders` kind mode=WRITE, and a WRITE needs its
    # own explicit grant; splitting them is what lets one line approve a read.
    KIND_WHAT="ORDER_SUMMARY 1회 재수집 — orderItems[].sellerProductId 유무·충전율과 channel_order_products 생성까지 (이미 연결된 계정에서 시작, 자격증명은 다루지 않는다)" ;;
  *)
    echo "BOOTSTRAP FAIL — unknown run kind '$KIND'. Use 'orders', 'orders-resync', 'inquiries' or 'inquiries-dedupe'."
    exit 1 ;;
esac

RUN_ID="cp-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
GIT_COMMIT="$(git -C "$HERE" rev-parse --short HEAD 2>/dev/null || echo unknown)"
DB_ALIAS="${SELLEROPS_COUPANG_DB_ALIAS:-coupang_proof}"
BACKEND_ORIGIN="${SELLEROPS_COUPANG_BACKEND_ORIGIN:-http://127.0.0.1:18091}"
FRONTEND_ORIGIN="${SELLEROPS_COUPANG_FRONTEND_ORIGIN:-http://localhost:5173}"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/bootstrap.sh — shared run identity for backend + preflight. Do NOT commit.
COUPANG_RUN_ID=$RUN_ID
COUPANG_APPROVAL_ID=$APPROVAL_ID
COUPANG_GIT_COMMIT=$GIT_COMMIT
COUPANG_DB_ALIAS=$DB_ALIAS
COUPANG_BACKEND_ORIGIN=$BACKEND_ORIGIN
COUPANG_FRONTEND_ORIGIN=$FRONTEND_ORIGIN
COUPANG_RUN_KIND=$KIND
ENV

echo "coupang live-proof bootstrap complete → $RUN_ENV"
echo
echo "  run id     : $RUN_ID"
echo "  approval id: $APPROVAL_ID  (arms the backend live-call interlock; binds the operator grant)"
echo "  git commit : $GIT_COMMIT"
echo "  run kind   : $KIND  ($KIND_WHAT)"
echo "  db alias   : $DB_ALIAS"
echo "  backend    : $BACKEND_ORIGIN"
echo "  frontend   : $FRONTEND_ORIGIN"
echo
echo "next: run-backend-local.sh, then start the frontend, then preflight.sh (all read $RUN_ENV)."
echo "the operator enters the real Coupang credential in the frontend at: $FRONTEND_ORIGIN/connect/coupang"
