/**
 * <b>The Canonical Product Source wired into Grounded Conversation.</b>
 *
 * Every assertion here stands on `contracts/product-truth/v1/ledger.json` — the reviewed ledger,
 * serialized by the same catalog the endpoint serves and regenerated by a backend test when it moves.
 * That is deliberate: a hand-typed fixture of 83 approved items would be a second copy of the ledger,
 * and a second copy going stale is the defect this whole package exists to end. When someone edits a
 * YAML row, the backend regenerates this file and these tests speak about the new content.
 *
 * <b>What is being pinned.</b> Not the wording of an answer — a model writes that and no test can own
 * it. What is pinned is which reviewed items a turn is ALLOWED to stand on, that a runtime posture
 * stands beside a capability instead of replacing it, and that the two layers stay distinguishable in
 * the log afterwards.
 */
import { describe, expect, it } from "vitest";
import { TOKEN, harness, say } from "./support";
import { CONVERSATION_PLANS, RECORDED_PLANS, SCENARIO_PLANS, capabilityPlan } from "../support/recordedPlans";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { CanonicalProductTruth } from "../../src/spring/types";
import {
  planSelection, selectCanonicalFacts,
} from "../../src/operator/capability/CanonicalProductTruth";
import type { CanonicalSelection } from "../../src/operator/capability/CanonicalProductTruth";
import { productFactSheet } from "../../src/operator/capability/ProductFactSheet";
import type { ChannelObjectTruth, SelfKnowledgeInputs } from "../../src/operator/capability/ProductTruth";

const LEDGER: CanonicalProductTruth = JSON.parse(
  readFileSync(resolve(__dirname, "../../../contracts/product-truth/v1/ledger.json"), "utf8"),
);

const NAMES = { NAVER: "네이버 스마트스토어", CAFE24: "카페24", COUPANG: "쿠팡" };

function facts(selection: Partial<CanonicalSelection>) {
  const plan = planSelection({ aspect: null, channel: null, focusObject: null, ...selection });
  return { plan, facts: selectCanonicalFacts(LEDGER, plan, NAMES) };
}

function textOf(selection: Partial<CanonicalSelection>, id: string): string {
  const found = facts(selection).facts.find((f) => f.id === id);
  expect(found, `${id} 가 선택되지 않았습니다`).toBeDefined();
  return found!.text;
}

describe("canonical selection — which reviewed items a turn may stand on", () => {
  it("the ledger it stands on is the reviewed one", () => {
    // If this fails the contract file was not regenerated, and every assertion below is about
    // something other than what a person approved.
    expect(LEDGER.capabilities).toHaveLength(48);
    expect(LEDGER.features.length).toBeGreaterThan(0);
    expect(LEDGER.directions.length).toBeGreaterThan(0);
    expect(LEDGER.roadmap.length).toBeGreaterThan(0);
  });

  /** §10-1. The regression the whole ledger was built for: Cafe24 is the one channel with a review API. */
  it("a Cafe24 review question stands on the AUTOMATIC acquisition row", () => {
    const text = textOf({ aspect: "CHANNEL_ACTION", channel: "CAFE24" }, "CAFE24.REVIEW.ACQUISITION");
    expect(text).toContain("자동으로 가져올 수 있습니다");
    expect(text).toContain("카페24");
  });

  /**
   * §10-2. A channel with no reply feature at all. The distinction the row has to keep making is
   * "the channel does not have it" versus "we have not switched it on" — the second is a promise.
   */
  it("Coupang review replies are refused as a channel fact, not as a switch", () => {
    const text = textOf({ aspect: "CHANNEL_ACTION", channel: "COUPANG" }, "COUPANG.REVIEW.EXECUTION");
    expect(text).toContain("기능이 없습니다");
    expect(text).toContain("설정이 꺼져 있어서가 아니라");
    expect(text).toContain("나중에 켤 수 있는 스위치가 아닙니다");
    // And no draft is prepared for a review nobody can ever answer.
    expect(textOf({ aspect: "CHANNEL_ACTION", channel: "COUPANG" }, "COUPANG.REVIEW.DRAFT"))
      .toContain("답변 초안도 준비하지 않습니다");
  });

  /**
   * §10-3. NAVER 문의 is three contracts, and the parent row is PARTIAL because one of them has no
   * path. A selection that sent the parent alone would hand the model the exact over-generalisation the
   * ledger's validator refuses to let anyone write into a file.
   */
  it("NAVER inquiry never travels as one generalised SUPPORTED row", () => {
    for (const aspect of ["CHANNEL_ACTION", "AFTER_CONNECT", null] as const) {
      const selected = facts({ aspect, channel: "NAVER" }).facts;
      const parentIds = new Set(selected.map((f) => f.id).filter((id) => /^NAVER\.INQUIRY\.[A-Z]+$/.test(id)));
      expect(parentIds.size, `${aspect}`).toBeGreaterThan(0);
      for (const parentId of parentIds) {
        // <b>Asked of the ROW, because a long row is rendered as several lines.</b> A row over the
        // backend floor's per-line cap is split at its own clause boundaries, so the caveat lives on
        // one part and the preconditions on another. The property is not "every line repeats the
        // caveat" — it is that no line CLAIMS the path without it, which is asserted directly below.
        const parts = selected.filter((f) => f.id === parentId);
        expect(parts.map((p) => p.text).join(" "), parentId).toContain("실제 사실은 subtype 이 정합니다");
        // The claim and its admission ticket are one line. A part that states what the product does
        // here — the row's seller-facing notes — carries the caveat in the same string, so a model
        // cannot be handed the capability with the qualification a clause away.
        for (const part of parts) {
          if (part.text.includes("답변을 직접 등록하고")) {
            expect(part.text, parentId).toContain("실제 사실은 subtype 이 정합니다");
          }
        }
        // …and the subtypes actually travel with it.
        const subtypes = selected.filter((f) => f.id.startsWith(`${parentId}.`));
        expect(subtypes.map((s) => s.id), parentId).toContain(`${parentId}.TALKTALK`);
        expect(subtypes.find((s) => s.id.endsWith(".TALKTALK"))!.text).toContain("톡톡");
      }
    }
  });

  /** §10-5. A decided direction is not something the product does today. */
  it("every direction announces itself as a direction", () => {
    const selected = facts({ aspect: null }).facts.filter((f) => f.category === "DIRECTION");
    expect(selected.length).toBeGreaterThan(0);
    for (const d of selected) {
      expect(d.text, d.id).toContain("제품 방향(이미 정한 방식이고, 지금 되는 기능에 대한 설명이 아닙니다)");
    }
  });

  /** §10-6. A future item carries the ledger's own hedge, every time it is mentioned. */
  it("every roadmap item travels with its qualifier and its own denial", () => {
    const selected = facts({ aspect: null }).facts.filter((f) => f.category === "ROADMAP");
    expect(selected.length).toBe(LEDGER.roadmap.length);
    for (const r of selected) {
      expect(r.text, r.id).toContain("앞으로의 방향(현재 제공되는 기능이 아닙니다)");
      const item = LEDGER.roadmap.find((x) => x.id === r.id)!;
      expect(r.text, r.id).toContain(item.qualifier.replace(/\s+/g, " ").trim());
    }
  });

  /** §10-7. A question the planner could not place gets the narrative — including this one. */
  it("an unplaced product question stands on the narrative", () => {
    const { plan, facts: selected } = facts({ aspect: null });
    expect(plan.categories).toContain("NARRATIVE");
    expect(selected.map((f) => f.id)).toContain("NARRATIVE.SELLER_CENTER_DIFFERENCE");
  });

  /**
   * §10-9. The point of selecting at all. A channel question is answered from that channel's rows and
   * the invariants — not from the whole approved ledger.
   */
  it("a channel question does not send the whole ledger", () => {
    const { plan, facts: selected } = facts({ aspect: "CHANNEL_ACTION", channel: "CAFE24" });
    const ids = selected.map((f) => f.id);
    expect(plan.categories).toEqual(["CAPABILITY", "INVARIANT"]);
    expect(ids.some((id) => id.startsWith("NARRATIVE."))).toBe(false);
    expect(ids.some((id) => id.startsWith("ROADMAP."))).toBe(false);
    expect(ids.some((id) => id.startsWith("DIRECTION."))).toBe(false);
    expect(ids.some((id) => id.startsWith("FEATURE."))).toBe(false);
    expect(ids.some((id) => id.startsWith("NAVER."))).toBe(false);
    // And even the widest selection is smaller than the ledger: half the capability rows are the two
    // axes a summary does not carry.
    const widest = facts({ aspect: null }).facts.length;
    const everyItem = LEDGER.capabilities.length + LEDGER.features.length + LEDGER.invariants.length
      + LEDGER.narratives.length + LEDGER.directions.length + LEDGER.roadmap.length;
    expect(widest).toBeLessThan(everyItem);
    expect(selected.length).toBeLessThan(widest);
  });

  /**
   * <b>Evidence is carried and never spoken.</b> A seller reads 「실제 몰에 게시한 적이 없습니다」, never
   * 「IMPLEMENTED」 — and an item that lost its Korean caveat does not travel at all.
   */
  it("no evidence level ever reaches a fact line", () => {
    for (const aspect of [null, "PRODUCT_OVERVIEW", "CHANNEL_ACTION", "AFTER_CONNECT", "SUPPORTED_CHANNELS",
      "HOW_TO_CONNECT"] as const) {
      for (const f of facts({ aspect, channel: "CAFE24" }).facts) {
        expect(f.text, f.id).not.toMatch(/LIVE_PROVEN|TEST_PROVEN|IMPLEMENTED|DECLARED/);
        expect(f.text, f.id).not.toMatch(/SUPPORTED|PARTIAL|NOT_SUPPORTED|UNKNOWN/);
      }
    }
  });

  it("an implemented capability keeps the sentence that says it has not been run", () => {
    // The Cafe24 review comment lane: built, never posted to any shop. The ledger says both, and the
    // second half is the one a seller needs.
    const text = textOf({ aspect: "CHANNEL_ACTION", channel: "CAFE24" }, "CAFE24.REVIEW.EXECUTION");
    expect(text).toContain("게시한 적이 없습니다");
  });

  it("an execution row carries its preconditions as their own clause", () => {
    const text = textOf({ aspect: "CHANNEL_ACTION", channel: "CAFE24" }, "CAFE24.INQUIRY.EXECUTION");
    expect(text).toContain("실행하려면:");
    expect(text).toContain("동의");
    // A precondition names what a seller can act on, never a configuration key.
    expect(text).not.toMatch(/mall\.|shop_no|client_ip|SELLEROPS_/);
  });
});

/* ─────────────────────── the two layers, side by side ─────────────────────── */

function inputs(overrides: Partial<SelfKnowledgeInputs> = {}): SelfKnowledgeInputs {
  return {
    registeredTools: ["get_inbox_summary"],
    actionClasses: ["READ"],
    readiness: { kind: "WORKING", connected: ["카페24"], connectable: [], delegable: [] },
    coverage: [
      { channelCode: "CAFE24", channelNameKo: "카페24", dataType: "INQUIRY", supported: true,
        connected: true, routineEnabled: true, state: "FRESH", rows: 10, openRows: 2 } as never,
    ],
    posture: { schedulerRunning: true, routineProvisioning: true },
    ...overrides,
  };
}

/** A Cafe24 inquiry whose execution this deployment has NOT switched on. */
const EXECUTION_OFF: ChannelObjectTruth = {
  channelCode: "CAFE24", channelName: "카페24", object: "INQUIRY", connected: true,
  support: { support: "SUPPORTED", reason: null } as never,
  acquisition: "AUTOMATIC", guidedPath: null,
  execution: "SELLER_FINAL_SUBMIT", executionReason: "EXECUTION_DISABLED",
};

describe("runtime overlay — beside the capability, never on top of it", () => {
  /**
   * §10-4. The sentence this package was written to stop being possible: a deployment with execution
   * off once produced 「reviewnary는 직접 전송하지 못합니다」 — a posture described as a specification.
   */
  it("execution being off here does not erase the reviewed DIRECT_WITH_APPROVAL", () => {
    const plan = planSelection({ aspect: "CHANNEL_ACTION", channel: "CAFE24", focusObject: null });
    const sheet = productFactSheet(inputs(), [EXECUTION_OFF], { facts: selectCanonicalFacts(LEDGER, plan, NAMES) });
    const keys = sheet.map((f) => f.key);

    // The capability is still there, and still says what the product does after approval.
    const capability = sheet.find((f) => f.key === "CAFE24.INQUIRY.EXECUTION")!;
    expect(capability).toBeDefined();
    expect(capability.text).toContain("직접 등록");

    // And beside it — not instead of it — the state of this deployment.
    const overlay = sheet.find((f) => f.key === "RUNTIME.CAFE24.INQUIRY.EXECUTION")!;
    expect(overlay).toBeDefined();
    expect(overlay.text).toContain("켜져 있지 않습니다");
    expect(keys.indexOf("CAFE24.INQUIRY.EXECUTION")).toBeLessThan(
      keys.indexOf("RUNTIME.CAFE24.INQUIRY.EXECUTION"));
  });

  /** §10-8. Whether it is running is always said, and it is the overlay that says it. */
  it("the collection posture travels on every canonical turn", () => {
    const plan = planSelection({ aspect: null, channel: null, focusObject: null });
    const sheet = productFactSheet(inputs(), [], { facts: selectCanonicalFacts(LEDGER, plan, NAMES) });
    const keys = sheet.map((f) => f.key);
    expect(keys).toContain("RUNTIME.COLLECTION");
    expect(keys).toContain("SELLER.COLLECTION");
    expect(keys).toContain("SELLER.READINESS");
  });

  /**
   * <b>Whether work is prepared before the seller asks is a deployment fact, and it is said only when
   * it was read.</b> The ledger's own feature row defers this question to the overlay, so without a
   * reading the Agent said 「이 환경에서 켜져 있는지는 여기서 확인되지 않습니다」 about something this
   * process knows. A backend that predates the field still says nothing — guessing 「꺼져 있습니다」 from
   * an absent boolean would be this layer inventing an outage.
   */
  it("the proactive posture is stated when read and absent when not", () => {
    const plan = planSelection({ aspect: null, channel: null, focusObject: null });
    const canonical = { facts: selectCanonicalFacts(LEDGER, plan, NAMES) };
    const sheetOf = (posture: unknown) =>
      productFactSheet({ ...inputs(), posture } as never, [], canonical);

    const off = sheetOf({ schedulerRunning: false, routineProvisioning: false, proactiveRunning: false });
    expect(off.find((f) => f.key === "RUNTIME.PROACTIVE")?.text).toContain("켜져 있지 않습니다");

    const on = sheetOf({ schedulerRunning: true, routineProvisioning: true, proactiveRunning: true });
    expect(on.find((f) => f.key === "RUNTIME.PROACTIVE")?.text).toContain("켜져 있습니다");

    // Older backend, and a missing posture entirely: no sentence at all.
    const older = sheetOf({ schedulerRunning: false, routineProvisioning: false });
    expect(older.map((f) => f.key)).not.toContain("RUNTIME.PROACTIVE");
    expect(sheetOf(null).map((f) => f.key)).not.toContain("RUNTIME.PROACTIVE");
  });

  /**
   * <b>One fact, one line.</b> With the ledger present the derived product-level sentences are not
   * emitted — two copies of one fact in one payload is how the older one goes stale unnoticed.
   */
  it("the derived product lines step aside for the reviewed ones", () => {
    const plan = planSelection({ aspect: "PRODUCT_OVERVIEW", channel: null, focusObject: null });
    const keys = productFactSheet(inputs(), [], { facts: selectCanonicalFacts(LEDGER, plan, NAMES) }).map((f) => f.key);
    for (const retired of ["PRODUCT.IDENTITY", "PRODUCT.AREAS", "PRODUCT.ORDER_SCOPE",
      "PRODUCT.READ_ONLY_OBJECTS", "PRODUCT.DATA_BOUNDARY", "PRODUCT.APPROVAL_BOUNDARY",
      "PRODUCT.DRAFT_BASIS", "PRODUCT.CONVERSATION_BOUNDARY"]) {
      expect(keys, retired).not.toContain(retired);
    }
    // The one product fact the ledger does not hold stays, because dropping a true fact because a file
    // does not repeat it would be the wrong direction.
    expect(keys).toContain("PRODUCT.OBJECT_IDENTITY");
    expect(keys).toContain("INVARIANT.APPROVAL_BOUNDARY");
  });

  /**
   * §9 of the brief. A missing ledger is not a reason to fall back to something narrower — it is the
   * state every deployment was in before this wiring, and the sheet it built still works.
   */
  it("without a ledger the sheet is exactly what it was before", () => {
    const keys = productFactSheet(inputs(), [], null).map((f) => f.key);
    expect(keys).toContain("PRODUCT.APPROVAL_BOUNDARY");
    expect(keys).toContain("PRODUCT.ORDER_SCOPE");
    expect(keys).toContain("PRODUCT.CONVERSATION_BOUNDARY");
    expect(keys.some((k) => k.startsWith("INVARIANT."))).toBe(false);
    expect(keys.some((k) => k.startsWith("RUNTIME.CAFE24."))).toBe(false);
  });
});

/* ─────────────────────── the whole turn, through the real lane ─────────────────────── */

describe("a product turn stands on the reviewed ledger end to end", () => {
  const ASKED = "카페24 리뷰는 자동으로 가져와?";
  const PLANS = {
    ...RECORDED_PLANS, ...CONVERSATION_PLANS, ...SCENARIO_PLANS,
    [ASKED]: capabilityPlan("카페24 리뷰 수집", "CHANNEL_ACTION", "CAFE24"),
  };

  it("the facts that reach the model are the approved ones, and the runtime state stands beside them", async () => {
    const h = harness({
      plansByGoal: PLANS,
      productTruth: LEDGER,
      converse: { available: true, answer: "카페24 구매후기는 자동으로 가져올 수 있습니다.", providerVersion: "t" },
    });
    const { conversationId: id } = await h.service.create(TOKEN);

    await say(h, id, ASKED);

    expect(h.operator.calls.productTruth).toBe(1);
    const sent = h.operator.converseRequests[0]!.facts;
    // The reviewed capability sentence, verbatim from the ledger.
    const row = LEDGER.capabilities.find((c) => c.id === "CAFE24.REVIEW.ACQUISITION")!;
    expect(sent.some((f) => f.includes(row.sellerFacingNotes[0]!))).toBe(true);
    // …and the layer the ledger cannot know, in its own line rather than folded into that one.
    expect(sent.some((f) => f.includes("정기") || f.includes("수집"))).toBe(true);
    // Selection did its job: another channel's capability rows are not in this payload. (Its
    // CONNECTION state still is — that is the overlay, and which channels exist is a runtime fact.)
    expect(sent.some((f) => f.includes("쿠팡 리뷰 답변 보내기"))).toBe(false);
    expect(sent.some((f) => f.includes("네이버 스마트스토어 문의 가져오기"))).toBe(false);
    // And no reviewed item is repeated by an older derived copy of itself.
    expect(sent.some((f) => f.includes("제가 다루는 핵심 운영 데이터는"))).toBe(false);
  });

  it("a turn with no ledger sends the derived facts and says so in the log", async () => {
    // The §9 posture: a backend without the endpoint is not a failure to fall back from, it is the
    // state every deployment was in before this wiring — and the lane still answers.
    const h = harness({
      plansByGoal: PLANS,
      converse: { available: true, answer: "카페24 구매후기는 자동으로 가져올 수 있습니다.", providerVersion: "t" },
    });
    const { conversationId: id } = await h.service.create(TOKEN);

    const { turn } = await say(h, id, ASKED);

    expect(turn.message).toContain("자동으로 가져올 수 있습니다");
    expect(h.operator.calls.converse).toBe(1);
    expect(h.operator.calls.productTruth).toBe(0);
  });

  it("the ledger is read once per service, not once per turn", async () => {
    const h = harness({
      plansByGoal: PLANS,
      productTruth: LEDGER,
      converse: { available: true, answer: "카페24 구매후기는 자동으로 가져올 수 있습니다.", providerVersion: "t" },
    });
    const { conversationId: id } = await h.service.create(TOKEN);

    await say(h, id, ASKED);
    await say(h, id, ASKED);

    expect(h.operator.calls.converse).toBe(2);
    expect(h.operator.calls.productTruth).toBe(1);
  });
});
